package Project.Base;

/**
 * Created by Leon on 19/01/2019.
 */
public enum Line {
    FORWARD1,FORWARD2,FORWARD3,FORWARD4,DEFENCE1,DEFENCE2,DEFENCE3,DEFENCE4,PPFORWARD1,PPFORWARD2,PPDEFENCE1,PPDEFENCE2,FORWARD14V4,FORWARD24V4,
    DEFENCE14V4,DEFENCE24V4,PK3FORWARD1,PK3FORWARD2,PK3DEFENCE1,PK3DEFENCE2,GOALIES,PENALTYSHOTS,EXTRAFORWARDS,EXTRADEFENCE,
    LASTMINOFFENCESIVEFORWARDS,LASTMINOFFENSIVEDEFENCE,LASTMINDEFENCIVEFORWAD,LASTMINDEVENCIVEDEFENCE
}
